### ISSUE TITLE
不能修改qbittorrent监听端口

### ISSUE THREAD

**Issue by SunOwen** [Mythologyli/qBittorrent-NAT-TCP-Hole-Punching#1]
您好！非常感谢您的工作！
我尝试了您的脚本，发现qbittorrent的监听端口未发生改变。粗略查阅了一些资料发现需要将原代码第15行：
`qb_cookie=$(curl -s -i --header "Referer: localhost:$qb_web_port" --data "username=$qb_username&password=$qb_password" http://localhost:$qb_web_port/api/v2/auth/login | grep -i set-cookie | cut -c13-48)`
修改为：
`qb_cookie=$(curl -s -i --header "Referer: http://localhost:$qb_web_port" --data "username=$qb_username&password=$qb_password" http://localhost:$qb_web_port/api/v2/auth/login | grep -i set-cookie | cut -c13-48)`
否则无法有效获取到set-cookie。在修改后，我的qbittorrent正确地更改了端口，供您参考。

**Comment by Mythologyli** [comment]
感谢回复！
不知道为啥我之前尝试成功了，我的版本为 4.5.0
我会进行修改，再次感谢！

**Comment by Mythologyli** [comment]
已修改
