### ISSUE TITLE
是否应该在 README 中提下 UPnP, NAT-PMP, PCP？

### ISSUE THREAD

**Issue by AnLuoRidge** [Mythologyli/qBittorrent-NAT-TCP-Hole-Punching#12]
UPnP, NAT-PM, PCP 这三个协议的目的和本方案非常类似，主要的区别是他们不依赖 STUN 服务器。我觉得可以在 README 中提一下：如果读者所用的网络设备无法应用上述三个协议，那么本方案是个不错的补充。

**Comment by Mythologyli** [comment]
如果用户没有公网 IP 只有 NAT1 环境，则只能使用 natmap 这样的打洞方案而无法使用 UPnP 等技术，因为运营商的 NAT 设备几乎肯定不会启用 UPnP。反之，如果用户有公网 IP，则只需在路由器上启用 UPnP，而无需打洞

我感觉能看到这个 repo 的人应该都属于没有公网 IP 的情况

**Comment by AnLuoRidge** [comment]
有道理。不过从 SEO 的角度讲，这几个关键词有助于本方案被绝望的用户搜索到。
