### ISSUE TITLE
关于操作系统的要求

### ISSUE THREAD

**Issue by zaozaolee** [Mythologyli/qBittorrent-NAT-TCP-Hole-Punching#14]
hello，小白想咨询下，这个运行的前提是不是要在linux环境下？
如果想在Windows电脑上用，有需要哪些前置条件吗？
谢谢啦！

**Comment by zaozaolee** [comment]
想起来，如果在macOS上，前置条件是否会简单些？转用macOS也行。
再次感谢！

**Comment by Mythologyli** [comment]
仅适配了 Linux，可以根据原理自行研究
