### ISSUE TITLE
关于natmap https://github.com/heiher/natmap/issues/27 的问题

### ISSUE THREAD

**Issue by qihang518887** [Mythologyli/qBittorrent-NAT-TCP-Hole-Punching#15]
在运行脚本后，如果映射发生变化会提示
[E] hev_sock_client_tcp src/hev-sock.c:183 Cannot assign requested address, Please check is another instance exists or wait a minute. More: https://github.com/heiher/natmap/issues/27
[E] tnsk_run src/hev-tnsk.c:107 Start TCP keep-alive service failed.
查看natmap的issues发现是TCP的TIME_WAIT，能否通过绑定动态端口避免这种情况发生

**Comment by Mythologyli** [comment]
抱歉回复晚了

按照我的理解，这应该是启动 natmap 采用何种参数的问题？

```bash
sudo ./natmap -s stunserver.stunprotocol.org -h bing.com -b 0 -e ./update.sh
```

启动 natmap 时采用 ``-b 0`` 即可避免此问题。但是你说“在运行脚本后，如果映射发生变化”会产生此问题，我感觉这个问题应该是关闭 natmap 后使用相同端口再次启动时才会发生的，能再详细说说吗
