### ISSUE TITLE
疑问，这样成功后，qb的传入连接显示的源地址是不是真实的源地址呢，会不会被修改为NAT设备（本地或运营商的）的地址呢

### ISSUE THREAD

**Issue by rankaiyx** [Mythologyli/qBittorrent-NAT-TCP-Hole-Punching#2]
您好！非常感谢您的工作！
如题，我有一个疑问。
我有一个类似的环境，是使用frp内网穿透或socat+n2n端口转发qb的监听端口到公网ip，虽然都能工作，但都会导致来源ip被修改（显然如此，源地址被修改了）。
我也考虑过，是否只进行目的地址转换，也就是iptables的DNAT，就可以解决这个问题，但n2n+iptables的DNAT不知什么原因，一直没有弄成功。
如果本项目能获得真实的源地址，那我基本判断，只进行DNAT应该是可以获得真实的源地址的，那我就可以继续尝试解决这个问题，否则就只能接受这个缺陷了。

**Comment by Mythologyli** [comment]
我感觉 qBittorrent 显示的是真实的源地址

**Comment by rankaiyx** [comment]
好的 谢谢
