### ISSUE TITLE
[BUG]重新打洞后，转发失效（附上解决办法）

### ISSUE THREAD

**Issue by MFWT** [Mythologyli/qBittorrent-NAT-TCP-Hole-Punching#3]
首先感谢作者大大的脚本，让我一介移动用户也能玩上PT

背景：连续在线一段时间后，运营商会给你更换IP（强制重新拨号）。以及日常生活中有时候需要插拔光猫（比如今天我就重新整理了下布线），这个时候Natter会重新打洞以保持连通性。

问题在于，脚本中有这么一句：

```shell
iptables -t nat -A PREROUTING -p tcp --dport $private_port -j REDIRECT --to-port $public_port
```

在natter重新打洞后会执行一次脚本，也就相当于重新执行了一次这条命令。由于这条命令是在**PREROUTING链尾**插入的，而原来的转发规则在这条新插入的链之上，也就是说iptables会优先匹配到原来的链，显然，新插入的链就没用了。而由于此时qBittorrent的监听端口已经改变，原来的转发规则也失效了，就表现为『打洞不成功』，实际上则是没装发过去。

解决方法也很简单，我能想到的有两个：
1.调整一下这条转发命令 **（-A 改成 -I）**，让他在链头插入：
```shell
iptables -t nat -I PREROUTING -p tcp --dport $private_port -j REDIRECT --to-port $public_port
```

2.在添加转发之前，列出所有PREROUTING规则，并先删掉上一次的转发规则，再添加
```shell
LINE=$(iptables -t nat -nvL --line-number | grep ${private_port} | head -n 1 -)
LINE_NUMBER=($LINE)
iptables -t nat -D PREROUTING $LINE_NUMBER
iptables -t nat -A PREROUTING -p tcp --dport $private_port -j REDIRECT --to-port $public_port #注意此处还是-A，用-I估计也行？
```

以上两种方法都可以解决这个问题
最后希望作者的脚本越做越好
谢谢！

**Comment by Mythologyli** [comment]
感谢！
之前发现有时候转发失效，只能改 private_port 完事，看来还是不懂 iptables

**Comment by MFWT** [comment]
> 感谢！ 之前发现有时候转发失效，只能改 private_port 完事，看来还是不懂 iptables

改Private_Port本质上其实还是『让新规则变成第一条链』从而匹配到这条链然后转发。这么做虽然也可以，但是长时间使用的话占用比较大（其实刚刚那我写的第一个方法，用久了也会占用大，只不过要很久很久才看得出来）。当然好在这些规则重启机器就清除了，所以问题不大。不过考虑到有些机器不能随便重启，还是删掉旧规则再添加比较好

**Comment by Mythologyli** [comment]
> > 感谢！ 之前发现有时候转发失效，只能改 private_port 完事，看来还是不懂 iptables
> 
> 改Private_Port本质上其实还是『让新规则变成第一条链』从而匹配到这条链然后转发。这么做虽然也可以，但是长时间使用的话占用比较大（其实刚刚那我写的第一个方法，用久了也会占用大，只不过要很久很久才看得出来）。当然好在这些规则重启机器就清除了，所以问题不大。不过考虑到有些机器不能随便重启，还是删掉旧规则再添加比较好

嗯！现在用的是第二种方法

**Comment by MFWT** [comment]
> 嗯！现在用的是第二种方法

抱歉抱歉，代码写错了
是
```shell
LINE=$(iptables -t nat -nvL --line-number | grep ${private_port} | head -n 1 -)
```
才对，原代码打多了个$，上面已经改过来了，update.sh也改一下吧
刚吃饱饭脑子不太好使（（（

**Comment by Mythologyli** [comment]
> > 嗯！现在用的是第二种方法
> 
> 抱歉抱歉，代码写错了 是
> 
> ```shell
> LINE=$(iptables -t nat -nvL --line-number | grep ${private_port} | head -n 1 -)
> ```
> 
> 才对，原代码打多了个$，上面已经改过来了，update.sh也改一下吧 刚吃饱饭脑子不太好使（（（

好，我去改一下。不怎么懂 bash 只能靠大佬（

**Comment by rankaiyx** [comment]
我用方法一成功了
方法二报错
update.sh: line 22: syntax error: unexpected "("

**Comment by rankaiyx** [comment]
line 22 指的是  LINE_NUMBER=($LINE)
不知道啥原因

**Comment by rankaiyx** [comment]
系统是 	OpenWrt 19.07.10

**Comment by rankaiyx** [comment]
不对  在路由器上运行  要用  DNAT  不能用 REDIRECT
