### ISSUE TITLE
readme与脚本注释不一致

### ISSUE THREAD

**Issue by iamydp** [Mythologyli/qBittorrent-NAT-TCP-Hole-Punching#4]
![image](https://user-images.githubusercontent.com/26623485/220931684-608f93b2-dc93-42bf-8850-2cdcb5ebe39b.png)
![image](https://user-images.githubusercontent.com/26623485/220931699-9fbdd0f1-006f-447a-a498-dc473f5679bd.png)
private port和public port那里

**Comment by Mythologyli** [comment]
改好了，可以自行参考两个项目的 README
