### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by wits-fe** [Mythologyli/qBittorrent-NAT-TCP-Hole-Punching#6]
> LINE=$(iptables -t nat -nvL --line-number | grep ${private_port} | head -n 1 -)
> LINE_NUMBER=($LINE)

这个有Bug，可以改为：
> LINE_NUMBER=$(iptables -t nat -nvL --line-number | grep ${private_port} | head -n 1 | grep -o '^[0-9]\+')

---------

其中建议
> iptables -t nat -A PREROUTING -p tcp --dport $private_port -j REDIRECT --to-port $public_port

改为
> iptables -t nat -I PREROUTING -p tcp --dport $private_port -j REDIRECT --to-port $public_port

使用 -I 命令从顶部插入规则，规则顺序自上而下
原先有一个默认的规则时，-A 命令从底部添加的规则可能永远不会执行，导致失败

**Comment by Mythologyli** [comment]
感谢！
